trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src
      - tests
      - pipelines/DocsCI.yml

pr: none

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '*.sln'
    feedsToUse: 'select'
    verbosityRestore: 'Minimal'

- task: DocFxTask@0
  displayName: 'Create DocFx Documentation'
  inputs:
    solution: 'docs/docfx.json'