trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src
      - tests
      - pipelines/DocsCI.yml

pool:
  vmImage: windows-2019

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: *.sln
    verbosityRestore: Normal

- task: DocFxTask@0
  displayName: 'Create DocFx Documentation'
  inputs:
    solution: docs/docfx.json