trigger: none

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  Solution: '*.sln'
  BuildConfiguration: 'Release'
  TestResultsDir: '$(Agent.TempDirectory)/TestResults'
  MergedReportDir: '$(Agent.TempDirectory)/TestResults/MergedCoverageReport'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare Analysis on SonarCloud'
  inputs:
    SonarCloud: 'SonarCloud Connection'
    organization: 'scherrer-home'
    scannerMode: 'MSBuild'
    projectKey: 'MyFirstRepository'
    projectName: 'MyFirstRepository'
    extraProperties: |
      sonar.test.exclusions=tests/
      sonar.coverageReportPaths=$(MergedReportDir)/SonarQube.xml
      sonar.cs.vstest.reportsPaths=$(TestResultsDir)/*.trx

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(Solution)'
    feedsToUse: 'select'
    verbosityRestore: 'Minimal'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(Solution)'
    arguments: '--no-restore --configuration $(BuildConfiguration)'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'ScherrerRegistry Connection'
    repository: 'MyFirstRepository'
    command: 'build'
    Dockerfile: 'src/*Web/Dockerfile'
    buildContext: 'src'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '$(Solution)'
    publishTestResults: false
    arguments: '--no-restore --no-build --configuration $(BuildConfiguration) --logger trx --collect "XPlat Code Coverage" --results-directory $(TestResultsDir)'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(TestResultsDir)/*.trx'
    mergeTestResults: true
    buildPlatform: 'Any CPU'
    buildConfiguration: '$(BuildConfiguration)'

- task: reportgenerator@4
  displayName: 'Merge Coverage Reports'
  inputs:
    reports: '$(TestResultsDir)/*/coverage.cobertura.xml'
    targetdir: '$(MergedReportDir)'
    reporttypes: 'Cobertura;SonarQube'
    assemblyfilters: '-*Tests*'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(MergedReportDir)/Cobertuna.xml'

- task: WhiteSource Bolt@20
  displayName: 'WhiteSource Bolt'
  inputs:
    cwd: 'src'

- task: SonarCloudAnalyze@1
  displayName: 'Analyze Code'

- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
  inputs:
    pollingTimeoutSec: '300'
