trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src
      - tests
      - pipelines/SonarCI.yml

pr: none

pool:
  vmImage: windows-2019

variables:
  Solution: *.sln
  BuildConfiguration: Release

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare Analysis on SonarCloud'
  inputs:
    SonarCloud: 'SonarCloud Connection'
    organization: scherrer-home
    scannerMode: MSBuild
    projectKey: MyFirstRepository
    projectName: MyFirstRepository
    extraProperties: |
      sonar.test.exclusions=tests/
      sonar.cs.vscoveragexml.reportsPaths=$(Agent.TempDirectory)/**/*.coveragexml
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(Solution)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(Solution)
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: tests/**/*.csproj
    arguments: '--collect "Code coverage" --configuration $(BuildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'Analyze Code'

- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
  inputs:
    pollingTimeoutSec: 300